$filePath = "postman/collections/Canvas LMS API Tests/Auth & Users/User Register.request.yaml"

$lines = @(
  '$kind: http-request',
  'url: "{{baseUrl}}/auth/register"',
  'method: POST',
  'headers:',
  '  Content-Type: application/json',
  'body:',
  '  type: text',
  '  content: |-',
  '    {',
  '      "name": "Hoc Sinh Moi",',
  '      "email": "student@example.com",',
  '      "password": "123456",',
  '      "role": "student"',
  '    }',
  'order: 1000',
  'scripts:',
  '  - type: afterResponse',
  '    language: text/javascript',
  '    code: |-',
  '      // Visualization script for User Register',
  '      var template = `',
  '      <style>',
  '        body { font-family: Arial, sans-serif; padding: 16px; background: #f5f5f5; }',
  '        .card { background: white; border-radius: 8px; padding: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); max-width: 600px; margin: auto; }',
  '        h2 { margin-top: 0; color: #333; }',
  '        .status { display: inline-block; padding: 4px 12px; border-radius: 12px; font-weight: bold; font-size: 14px; margin-bottom: 16px; }',
  '        .success { background: #d4edda; color: #155724; }',
  '        .error { background: #f8d7da; color: #721c24; }',
  '        table { width: 100%; border-collapse: collapse; margin-top: 12px; }',
  '        th { text-align: left; padding: 8px 12px; background: #f0f0f0; color: #555; font-size: 13px; border-bottom: 2px solid #ddd; }',
  '        td { padding: 8px 12px; border-bottom: 1px solid #eee; font-size: 14px; color: #333; }',
  '        td.key { font-weight: bold; color: #555; width: 35%; }',
  '        .token { font-family: monospace; font-size: 12px; word-break: break-all; color: #666; }',
  '        .warning { background: #fff3cd; color: #856404; padding: 12px; border-radius: 6px; font-size: 14px; }',
  '      </style>',
  '      <div class="card">',
  '        <h2>User Registration Result</h2>',
  '        <span class="status {{statusClass}}">HTTP {{statusCode}}</span>',
  '        {{#if isJson}}',
  '          {{#if hasError}}',
  '            <div class="warning">{{errorMessage}}</div>',
  '          {{else}}',
  '            <table>',
  '              <tr><th>Field</th><th>Value</th></tr>',
  '              {{#each fields}}',
  '              <tr><td class="key">{{key}}</td><td>{{{value}}}</td></tr>',
  '              {{/each}}',
  '            </table>',
  '          {{/if}}',
  '        {{else}}',
  '          <div class="warning">Response is not JSON. The server may have returned an HTML page or redirect. Check the response body tab for details.</div>',
  '        {{/if}}',
  '      </div>',
  '      `;',
  '      ',
  '      var statusCode = pm.response.code;',
  "      var statusClass = (statusCode >= 200 && statusCode < 300) ? 'success' : 'error';",
  '      var isJson = false;',
  '      var hasError = false;',
  "      var errorMessage = '';",
  '      var fields = [];',
  '      ',
  '      try {',
  '        var json = pm.response.json();',
  '        isJson = true;',
  '      ',
  '        if (json.error || (json.message && statusCode >= 400)) {',
  '          hasError = true;',
  "          errorMessage = json.error || json.message || 'An error occurred';",
  '        } else {',
  "          var skipKeys = ['password', 'hashedPassword'];",
  "          var tokenKeys = ['token', 'accessToken', 'access_token', 'refreshToken', 'refresh_token'];",
  '      ',
  '          Object.keys(json).forEach(function(key) {',
  '            if (skipKeys.indexOf(key) !== -1) return;',
  '            var value = json[key];',
  "            if (tokenKeys.indexOf(key) !== -1 && typeof value === 'string' && value.length > 20) {",
  "              value = value.substring(0, 30) + '...';",
  "            } else if (typeof value === 'object') {",
  '              value = JSON.stringify(value);',
  '            }',
  '            fields.push({ key: key, value: value });',
  '          });',
  '        }',
  '      } catch(e) {',
  '        isJson = false;',
  '      }',
  '      ',
  '      pm.visualizer.set(template, {',
  '        statusCode: statusCode,',
  '        statusClass: statusClass,',
  '        isJson: isJson,',
  '        hasError: hasError,',
  '        errorMessage: errorMessage,',
  '        fields: fields',
  '      });'
)

$content = $lines -join "`r`n"
[System.IO.File]::WriteAllText($filePath, $content, [System.Text.Encoding]::UTF8)
Write-Host "Done"
